chartConfig:
  config:
    label: Yellow Signals
    selectedField: fct_market_environment_count_yellow_signals
    showBigNumberLabel: true
  type: big_number
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: fct_market_environment
  filters: {}
  limit: 1
  metricOverrides: {}
  metrics:
    - fct_market_environment_count_yellow_signals
  sorts: []
  tableCalculations: []
name: Yellow Signals
slug: fa-env-yellow-count
spaceSlug: shared
tableConfig:
  columnOrder:
    - fct_market_environment_count_yellow_signals
tableName: fct_market_environment
version: 1
