chartConfig:
  config:
    label: Overall Risk Score (0–100)
    selectedField: mart_risk_monitor_composite_risk_score
    showBigNumberLabel: true
  type: big_number
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: mart_risk_monitor
  filters: {}
  limit: 1
  metricOverrides: {}
  metrics:
    - mart_risk_monitor_composite_risk_score
  sorts: []
  tableCalculations: []
name: Overall Risk Score
slug: fa-risk-score
spaceSlug: shared
tableConfig:
  columnOrder:
    - mart_risk_monitor_composite_risk_score
tableName: mart_risk_monitor
version: 1
