-- Migration: Rename existing RAW tables to follow {SOURCE}_{TYPE} convention.
-- Run once before loading new data.
-- Idempotent: uses IF EXISTS so safe to re-run.

USE DATABASE DB_TEAM_3;
USE WAREHOUSE WH_TEAM_3_XS;

-- FRED: FRED_SERIES_METADATA → FRED_METADATA
ALTER TABLE IF EXISTS RAW.FRED_SERIES_METADATA RENAME TO RAW.FRED_METADATA;

-- Yahoo Finance: MARKET_* → YAHOO_*
ALTER TABLE IF EXISTS RAW.MARKET_PRICES RENAME TO RAW.YAHOO_OBSERVATIONS;
ALTER TABLE IF EXISTS RAW.MARKET_METADATA RENAME TO RAW.YAHOO_METADATA;

-- World Bank: WORLDBANK_INDICATORS → WORLDBANK_OBSERVATIONS
ALTER TABLE IF EXISTS RAW.WORLDBANK_INDICATORS RENAME TO RAW.WORLDBANK_OBSERVATIONS;

-- Verify
SELECT TABLE_NAME, ROW_COUNT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'RAW'
ORDER BY TABLE_NAME;
